name: reqres_test
description: "Um projeto para teste que utiliza o reqres api"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.8
  logger: 1.3.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
   - assets/images/
